services:
  bot:
    image: "egormizerov/expansion_bot:latest"
    container_name: bot
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
      - redis
    network_mode: host

  redis:
    image: "redis:alpine"
    restart: "always"
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis/d–∞ta:/root/redis
      - /var/lib/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - bot

  postgres:
    image: "postgres"
    restart: "always"
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - bot

volumes:
  db:
    driver: local

networks:
  bot:
    driver: "bridge"