services:
  bot:
    build:
      dockerfile: Dockerfile
    container_name: bot
    restart: always
    ports:
      - "8081:8081"
    env_file: .env
    links:
      - postgres
      - redis
    depends_on:
      - migrations
      - postgres
      - redis

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.21.1
    env_file: .env
    links:
      - postgres
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

  redis:
    image: "redis:alpine"
    restart: "always"
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis/d–∞ta:/root/redis
      - /var/lib/redis/redis.conf:/usr/local/etc/redis/redis.conf

  postgres:
    image: "postgres"
    container_name: postgres
    restart: "always"
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local